export default {
  index: 'Overview',
  '-- setup': { type: 'separator', title: 'Set up' },
  'root-access': 'Open the Pod and get root',
  installation: 'Install and update',
  '-- use': { type: 'separator', title: 'Use the app' },
  navigation: 'Find your way around',
  temperature: 'Temp',
  autopilot: 'Autopilot',
  schedules: 'Schedule',
  biometrics: 'Sleep',
  system: 'System',
  settings: 'Settings',
  '-- technical': { type: 'separator', title: 'How it works' },
  'autopilot-engine': 'Autopilot engine',
  'data-flow': 'Follow your data',
  integrations: 'HomeKit and MQTT reference',
  mcp: 'MCP for agents',
}
